import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import '../theme/app_theme.dart';

class TermsPrivacyScreen extends StatefulWidget {
  final int initialTab; // 0 for Terms, 1 for Privacy

  const TermsPrivacyScreen({super.key, this.initialTab = 0});

  @override
  State<TermsPrivacyScreen> createState() => _TermsPrivacyScreenState();
}

class _TermsPrivacyScreenState extends State<TermsPrivacyScreen> with SingleTickerProviderStateMixin {
  late final TabController _tabController;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 2, vsync: this, initialIndex: widget.initialTab);
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppTheme.pageBackground,
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0,
        iconTheme: const IconThemeData(color: AppTheme.textPrimary),
        title: Text(
          'Legal & Compliance',
          style: GoogleFonts.poppins(fontSize: 18, fontWeight: FontWeight.bold, color: AppTheme.textPrimary),
        ),
        bottom: TabBar(
          controller: _tabController,
          indicatorColor: AppTheme.primaryViolet,
          labelColor: AppTheme.primaryViolet,
          unselectedLabelColor: AppTheme.textMuted,
          labelStyle: GoogleFonts.poppins(fontSize: 13, fontWeight: FontWeight.bold),
          unselectedLabelStyle: GoogleFonts.poppins(fontSize: 13, fontWeight: FontWeight.normal),
          tabs: const [
            Tab(text: 'Terms & Conditions'),
            Tab(text: 'Privacy Policy'),
          ],
        ),
      ),
      body: TabBarView(
        controller: _tabController,
        children: [
          // Terms & Conditions
          SingleChildScrollView(
            physics: const BouncingScrollPhysics(),
            padding: const EdgeInsets.all(20),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                _buildLegalSection(
                  '1. Platform Usage & Acceptance',
                  'By accessing and using the Propzen application, you agree to comply with all applicable Real Estate (Regulation and Development) Act (RERA) guidelines and Indian information technology laws. Propzen serves as an intelligence-first discovery and facilitation platform connecting buyers, owners, and verified dealers.',
                ),
                _buildLegalSection(
                  '2. RERA Compliance & Listings',
                  'All project listings displayed on Propzen include state RERA registration numbers where applicable. Users are advised to verify all statutory registrations directly on official state RERA portals (UPRERA / HRERA / Delhi RERA) before signing formal sale agreements.',
                ),
                _buildLegalSection(
                  '3. Pricing, Valuation & Market Intelligence',
                  'Valuations, fair price estimates, and rental yields generated by the Propzen 10X Intelligence Engine are based on historical registry records and predictive algorithms. These figures represent indicative advisory estimates.',
                ),
                _buildLegalSection(
                  '4. Site Visits & Bookings',
                  'Site visit bookings scheduled through Propzen are free of charge. Dealers and platform partners are strictly prohibited from soliciting unrecorded cash advances during site tours.',
                ),
              ],
            ),
          ),

          // Privacy Policy
          SingleChildScrollView(
            physics: const BouncingScrollPhysics(),
            padding: const EdgeInsets.all(20),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                _buildLegalSection(
                  '1. Information We Collect',
                  'We collect necessary information such as name, mobile number, email address, property preferences, and loan enquiry criteria solely to personalize your real-estate discovery and connect you with assigned property advisors.',
                ),
                _buildLegalSection(
                  '2. Zero Spam & Data Protection',
                  'Your personal phone number and contact details are encrypted and strictly guarded. We never sell customer lead databases to unsolicited third-party call centers.',
                ),
                _buildLegalSection(
                  '3. Bank Loan & KYC Document Security',
                  'Documents submitted for home loan eligibility or legal verification are stored in 256-bit encrypted lockers and accessed exclusively by certified banking partners with your explicit consent.',
                ),
                _buildLegalSection(
                  '4. Account Deletion & Data Rights',
                  'You have full ownership of your data. You may request account closure and permanent removal of personal history anytime via Settings or support@propzen.ai.',
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildLegalSection(String title, String content) {
    return Container(
      margin: const EdgeInsets.only(bottom: 16),
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: AppTheme.cardWhite,
        borderRadius: BorderRadius.circular(14),
        border: Border.all(color: AppTheme.borderLight),
        boxShadow: AppTheme.subtleCardShadow,
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(title, style: GoogleFonts.poppins(fontSize: 14, fontWeight: FontWeight.bold, color: AppTheme.textPrimary)),
          const SizedBox(height: 8),
          Text(content, style: GoogleFonts.inter(fontSize: 12, color: AppTheme.textSecondary, height: 1.6)),
        ],
      ),
    );
  }
}
