package com.propzen.crm.automation;

public enum AutomationEventType {
    LEAD_CREATED,
    LEAD_UPDATED,
    LEAD_ASSIGNED,
    LEAD_STAGE_CHANGED,
    ENQUIRY_CREATED,
    SITE_VISIT_BOOKED,
    SITE_VISIT_CONFIRMED,
    SITE_VISIT_COMPLETED,
    SITE_VISIT_REMINDER,
    SERVICE_REQUEST_CREATED,
    SERVICE_REQUEST_ASSIGNED,
    PAYMENT_RECEIVED,
    DOCUMENT_UPLOADED,
    SERVICE_COMPLETED,
    FOLLOW_UP_DUE,
    LEAD_STATUS_CHANGED,
    DEALER_ASSIGNED
}
