"""
Enums for PropZen GlobalVerificationEngine
"""
from enum import Enum


class DocumentType(str, Enum):
    SALE_DEED = "SALE_DEED"
    REGISTRY = "REGISTRY"
    REGISTRY_DOCUMENT = "REGISTRY_DOCUMENT"
    KHATAUNI = "KHATAUNI"
    KHATAUNI_LAND_RECORD = "KHATAUNI_LAND_RECORD"
    PROPERTY_TAX = "PROPERTY_TAX"
    PROPERTY_TAX_DOCUMENT = "PROPERTY_TAX_DOCUMENT"
    ENCUMBRANCE = "ENCUMBRANCE"
    ENCUMBRANCE_CERTIFICATE = "ENCUMBRANCE_CERTIFICATE"
    ALLOTMENT = "ALLOTMENT"
    ALLOTMENT_LETTER = "ALLOTMENT_LETTER"
    POSSESSION = "POSSESSION"
    POSSESSION_LETTER = "POSSESSION_LETTER"
    COURT_DOCUMENT = "COURT_DOCUMENT"
    GENERIC_PROPERTY_DOCUMENT = "GENERIC_PROPERTY_DOCUMENT"
    UNKNOWN = "UNKNOWN"


class VerificationStatus(str, Enum):
    PASS = "PASS"
    WARNING = "WARNING"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    HIGH_RISK = "HIGH_RISK"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    PENDING = "PENDING"


class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class FindingSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class FindingType(str, Enum):
    FIELD_MISMATCH = "FIELD_MISMATCH"
    INVALID_DATE_RELATIONSHIP = "INVALID_DATE_RELATIONSHIP"
    INVALID_NUMERIC_VALUE = "INVALID_NUMERIC_VALUE"
    UNRECOGNIZED_AREA_UNIT = "UNRECOGNIZED_AREA_UNIT"
    SUSPICIOUS_NAME_VARIATION = "SUSPICIOUS_NAME_VARIATION"
    MISSING_CRITICAL_FIELD = "MISSING_CRITICAL_FIELD"
    OCR_UNCERTAINTY = "OCR_UNCERTAINTY"
    UNSUPPORTED_FORMAT = "UNSUPPORTED_FORMAT"
    DUPLICATE_RECORD = "DUPLICATE_RECORD"
    UNKNOWN_DOCUMENT_TYPE = "UNKNOWN_DOCUMENT_TYPE"


class AIProviderType(str, Enum):
    SYNTHETIC = "synthetic"
    LOCAL = "local"
    GEMINI = "gemini"
    OPENAI = "openai"
