package com.propzen.service.model;

public enum ServiceJourneyEventType {
    REQUEST_CREATED,
    PARTNER_RECOMMENDED,
    PARTNER_ASSIGNED,
    PARTNER_ACCEPTED,
    PARTNER_REJECTED,
    DOCUMENT_REQUESTED,
    DOCUMENT_UPLOADED,
    DOCUMENT_VERIFIED,
    PAYMENT_PENDING,
    PAYMENT_RECEIVED,
    WORK_STARTED,
    MILESTONE_CREATED,
    MILESTONE_COMPLETED,
    REVISION_REQUESTED,
    SERVICE_COMPLETED,
    SERVICE_CANCELLED,
    FEEDBACK_SUBMITTED
}
