package com.propzen.ai.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;

import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * Persisted lead score generated by the AI lead scoring model.
 */
@Entity
@Table(name = "ai_lead_scores")
public class AiLeadScore implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    @Column(name = "lead_id", nullable = false)
    private UUID leadId;

    @Column(name = "score", nullable = false)
    private Integer score;

    @Column(name = "classification", nullable = false)
    private String classification;

    @Column(name = "reasons", columnDefinition = "TEXT")
    private String reasons;

    @Column(name = "next_action")
    private String nextAction;

    @Column(name = "confidence")
    private Double confidence;

    @Column(name = "scored_at", nullable = false, updatable = false)
    private OffsetDateTime scoredAt;

    public AiLeadScore() {
    }

    public AiLeadScore(UUID leadId, Integer score, String classification, String reasons, String nextAction, Double confidence) {
        this.leadId = leadId;
        this.score = score;
        this.classification = classification;
        this.reasons = reasons;
        this.nextAction = nextAction;
        this.confidence = confidence;
    }

    @PrePersist
    protected void onCreate() {
        if (scoredAt == null) {
            scoredAt = OffsetDateTime.now();
        }
    }

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public UUID getLeadId() {
        return leadId;
    }

    public void setLeadId(UUID leadId) {
        this.leadId = leadId;
    }

    public Integer getScore() {
        return score;
    }

    public void setScore(Integer score) {
        this.score = score;
    }

    public String getClassification() {
        return classification;
    }

    public void setClassification(String classification) {
        this.classification = classification;
    }

    public String getReasons() {
        return reasons;
    }

    public void setReasons(String reasons) {
        this.reasons = reasons;
    }

    public String getNextAction() {
        return nextAction;
    }

    public void setNextAction(String nextAction) {
        this.nextAction = nextAction;
    }

    public Double getConfidence() {
        return confidence;
    }

    public void setConfidence(Double confidence) {
        this.confidence = confidence;
    }

    public OffsetDateTime getScoredAt() {
        return scoredAt;
    }

    public void setScoredAt(OffsetDateTime scoredAt) {
        this.scoredAt = scoredAt;
    }
}
